[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/moby/moby"
revision = "7e59fbe50eaa5fd952f7a05aa827e2dc738c3794"

[[constraint]]
  name = "github.com/docker/go-units"
version = "0.3.2"

# match docker/distribution revision with moby
[[override]]
  name = "github.com/docker/distribution"
revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.8.2"
